### ISSUE TITLE
Goal: report errors in Github instead of Discord bot

### ISSUE THREAD

**Issue by zolotokrylin** [holdex/pr-time-tracker#267]
It is much better to report and discuss problems and solve these problems in Github instead of Discord.

<img width="717" alt="image" src="https://github.com/holdex/pr-time-tracker/assets/1125014/f2ae9757-f3d9-4a7d-9283-b72bd8747d0d">

**Comment by georgeciubotaru** [comment]
Hey @teodorus-nathaniel How much time will take for you this task? Just add the GitHub issue functionality and leave the existing Discord Bot.

**Comment by teodorus-nathaniel** [comment]
hi @georgeciubotaru, I think 1-2 days

**Comment by zolotokrylin** [comment]
What do you think about the priority here? Shall we invest our time in it, or is it unnecessary here?

**Comment by teodorus-nathaniel** [comment]
@zolotokrylin 
after I check it further, I think its easy to do, if there is no unexpected things, it should be ready today, so I think its fine to do this one

**Comment by zolotokrylin** [comment]
Got it. Let's do it. Thank you.

**Comment by teodorus-nathaniel** [comment]
@georgeciubotaru it seems that the staging supabase is down? could you check? its this one `postgresql://postgres.phtaofoaormwpxwrwtkw:YZHPcdhJEwOUcK05@aws-0-eu-central-1.pooler.supabase.com:6543/postgres?schema=triggerdotdev&pgbouncer=true`
![image](https://github.com/user-attachments/assets/bf9fa1ce-99b6-40a0-9cc5-e6f476955ed5)

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel Please check now

**Comment by zolotokrylin** [comment]
Great job, Teo!
