### ISSUE TITLE
Problem: unable to submit PR cost

### ISSUE THREAD

**Issue by Addis-Belete** [holdex/pr-time-tracker#304]
https://github.com/clearpool-finance/protocol-squid/issues/275

**Comment by zolotokrylin** [comment]
@Addis-Belete which PR? The issue you are referencing was deleted as an issue in the wrong repo

**Comment by Addis-Belete** [comment]
https://github.com/clearpool-finance/protocol-squid/pull/274#issuecomment-2440946484

**Comment by Addis-Belete** [comment]
Log: submitted after PR merged
