### ISSUE TITLE
Problem: Cannot see the bug events in the developers spreadsheet

### ISSUE THREAD

**Issue by teodorus-nathaniel** [holdex/pr-time-tracker#321]
Sub of
- #273

**Comment by teodorus-nathaniel** [comment]
@georgeciubotaru for this problem, I can't seem to find developer spreadsheet in the code, is this flow manually extracted from the DB?

**Comment by markholdex** [comment]
@teodorus-nathaniel feel free to agree on the technical implementation with @georgeciubotaru since he directs the development of this project.

**Comment by teodorus-nathaniel** [comment]
@markholdex @georgeciubotaru is there any way that I can check the google big query logs from my local?

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel there is the `/api/events` endpoint you can call to see the events.

Note: You can adjust it based on your needs, locally

**Comment by teodorus-nathaniel** [comment]
> Note: You can adjust it based on your needs, locally

also, what do you mean by this?

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel You need to add a new event type `BUG_INTRODUCED`

owner = `bug_author_username`
sender =  `reporter_username`
id = `commit_link`

other fields should be taken from Github event

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel 
> Note: You can adjust it based on your needs, locally

Update the API to return only the values inserted today, or only the values with action = BUG_INTRODUCED

**Comment by teodorus-nathaniel** [comment]
> @teodorus-nathaniel You need to add a new event type `BUG_INTRODUCED`
> 
> owner = `bug_author_username` sender = `reporter_username` id = `commit_link`
> 
> other fields should be taken from Github event

got it, but I still have 1 issue, because the `id` field is number, I can't put the commit link
so can I put it as `label` instead? and for the `id` I just put pr number like the other events?

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel The ideal case will be to obtain the PR number using the commit link.

**Comment by teodorus-nathaniel** [comment]
> @teodorus-nathaniel The ideal case will be to obtain the PR number using the commit link.

so you mean pr number is not a necessary data to put because its already inside commit link?
but it still doesn't solve the issue, where the id field type is number though, did I misunderstood what you meant?

**Comment by georgeciubotaru** [comment]
from commit link you can take the PR number value and use as `id`, that's all

**Comment by teodorus-nathaniel** [comment]
> from commit link you can take the PR number value and use as `id`, that's all

if that's the case, I can just use the pr number value from the github event itself right?

and for the commit link itself, put it as `label` is fine too?

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel 
The event should be scoped to the `PR` that introduced the bug, not to the one from GitHub event (fixes the bug) 

id: PR_number_introduced_bug
`label`: has a different usage, so no need to pass anything
repository, title, - should be based on id, meaning query PR info by id.

I hope you get my idea

**Comment by teodorus-nathaniel** [comment]
@georgeciubotaru ooh that's what I'm missing, thanks for the clarification,
still one thing I would like to ask, about the commit data/hash itself, you don't need to put it to the event data?

**Comment by teodorus-nathaniel** [comment]
> @teodorus-nathaniel The event should be scoped to the `PR` that introduced the bug, not to the one from GitHub event (fixes the bug)
> 
> id: PR_number_introduced_bug `label`: has a different usage, so no need to pass anything repository, title, - should be based on id, meaning query PR info by id.
> 
> I hope you get my idea

I also would like to make sure I understand correctly, so for example as a user the flow is:

- I found one bug and make PR number 500 to fix it.
- I use git blame and found that the bug originated from a commit from pr 306, and got the link `https://github.com/holdex/pr-time-tracker/pull/306/commits/a167761de0dfe2466265500ef7248ad5db102b55`
- I submit `@pr-time-tracker bug commit https://github.com/holdex/pr-time-tracker/pull/306/commits/a167761de0dfe2466265500ef7248ad5db102b55 && bug author @teodorus-nathaniel`
- when I close the PR, it will get the report and send an event like this:
```
{
  "id": 306,
  "created_at": "1731677877",
  "updated_at": "1731677877",
  "label": null,
  "index": 1,
  "organization": "holdex",
  "owner": "bug-creator-username",
  "sender": "reporter-username",
  "repository": "pr-time-tracker",
  "title": "The title for PR 306",
  "action": "BUG_INTRODUCED",
  "payload": null,
  "_id": "holdex/pr-time-tracker@306_BUG_INTRODUCED"
}
```

is that all correct? @georgeciubotaru

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel No need for commit data

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel All good: 🏆

`repository` and `organization` should also refer to the PR 306.

most of the time can be the same repo and organization.

**Comment by teodorus-nathaniel** [comment]
> I also would like to make sure I understand correctly, so for example as a user the flow is:
> 
> * I found one bug and make PR number 500 to fix it.
> * I use git blame and found that the bug originated from a commit from pr 306, and got the link `https://github.com/holdex/pr-time-tracker/pull/306/commits/a167761de0dfe2466265500ef7248ad5db102b55`
> * I submit `@pr-time-tracker bug commit https://github.com/holdex/pr-time-tracker/pull/306/commits/a167761de0dfe2466265500ef7248ad5db102b55 && bug author @teodorus-nathaniel`
> * when I close the PR, it will get the report and send an event like this:

hi @georgeciubotaru I'd like to confirm about this flow, is the part here correct?
> * I use git blame and found that the bug originated from a commit from pr 306, and got the link `https://github.com/holdex/pr-time-tracker/pull/306/commits/a167761de0dfe2466265500ef7248ad5db102b55`

Need to confirm again because to get the commit link, its takes a pretty long time, from my experience, its easy from vscode to get the PR its related to, but after you get the PR, its hard to pinpoint which commit leads to the bug. I need to check the commits one by one.

That's why I want to know if there is an easy way that you can get that commit link?

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel Using VSCode is okay, doesn't matter if we merge via squash, as the `main` branch commit is important here
