### ISSUE TITLE
Problem: Fix PR check runs on draft PR

### ISSUE THREAD

**Issue by teodorus-nathaniel** [holdex/pr-time-tracker#324]
Fix PR check run should not run on draft PR and PR body edit event.

PR body edited event won't have any affect on the Fix PR flow.

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel Please also fix this issue, is a top priority
<img width="605" alt="image" src="https://github.com/user-attachments/assets/7bb206bf-8bf7-4147-9cae-dfc2c8591e77">

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel For `On pull request` jobs too
