### ISSUE TITLE
Problem: Tracker mesage is not removed if the check is cancelled

### ISSUE THREAD

**Issue by georgeciubotaru** [holdex/pr-time-tracker#327]
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/b7b621b1-ac92-466e-8eef-f93bb13b60e0">

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel Can you please check if that is a bug or a missing feature?

**Comment by teodorus-nathaniel** [comment]
You mean when the pr title changes to non fix?

is the check itself cancelled, but the message not removed?

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel Yes

**Comment by teodorus-nathaniel** [comment]
Hi @georgeciubotaru is it possible for me to check the production logs?

Actually I'm having some trouble with running the project in my local.
When I setting up a new project, I usually see confirm that the project is setup correctly when I see there is a new run after I register the endpoint
![image](https://github.com/user-attachments/assets/8146fd18-bdf2-47db-bb73-abc4acce111c)

But I'm not sure why, I tried making multiple new projects but none of them have those run after I register the endpoint.

Do you know what possibly is the issue? Or how to trigger the webhook registering process manually?

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel Probably the webhook was removed, please try with different proxy address to register the webhooks

**Comment by teodorus-nathaniel** [comment]
Yeah I have tried with new proxy addresses, which I was hoping that it will register to github after I have registered the endpoint. But the issue is they didn't trigger the run to register the new proxy address

Is it working well for you?

**Comment by georgeciubotaru** [comment]
Log: I will check on my end

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel Mine looks that way:
<img width="585" alt="image" src="https://github.com/user-attachments/assets/697dd198-cf5b-40d3-ad11-aae5f7ab9121">

But does your telebit proxy URL work?, on my side it doesn't work

**Comment by teodorus-nathaniel** [comment]
@georgeciubotaru that telebit url was just a dummy from readme, the issue is that in my case, there is no run at all after the url register

so everything works well on your side? if thats the case ill try it again from the start

btw thanks for checking it out

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel The URL you are seeing is used by me locally.

**Comment by teodorus-nathaniel** [comment]
> @teodorus-nathaniel The URL you are seeing is used by me locally.

@georgeciubotaru yes for the url that I meant dummy was the image this image that I sent before.
![image](https://github.com/user-attachments/assets/8146fd18-bdf2-47db-bb73-abc4acce111c)

I just tried again using same flow as yesterday, but now I see the run 😅
So its looking all good now, thank you, will resume checking this issue up

**Comment by teodorus-nathaniel** [comment]
@georgeciubotaru sorry I just realized, now its getting weirder, so here's the steps that I did,
now it have 1 run after registering the url, but its really strange that its using your local telebit url 😓,

I have never copied your telebit url though, so I'm really not sure why is it like that.
Could you check out the steps I did in the video below and maybe see where the problem is?

https://github.com/user-attachments/assets/492aacd2-3391-4197-b0f5-2815b7221806

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel I can see you are using a custom project, did you also update the `package.json` file?

**Comment by teodorus-nathaniel** [comment]
> @teodorus-nathaniel I can see you are using a custom project, did you also update the `package.json` file?
> 
> <img alt="image" width="516" src="https://private-user-images.githubusercontent.com/8217518/388951957-2af459f2-48c8-47d1-9243-99b28ebb1d44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyODI4ODYsIm5iZiI6MTczMjI4MjU4NiwicGF0aCI6Ii84MjE3NTE4LzM4ODk1MTk1Ny0yYWY0NTlmMi00OGM4LTQ3ZDEtOTI0My05OWIyOGViYjFkNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjJUMTMzNjI2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM3ZTI0NjA4MWFlYWUzZTU4M2EwMzVjYWIzMGQ3NWM1MDRjODQ3ZThmM2ZkYTU3NWQ2NTY3MmY3YmQ2MWMxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.rsOE0MSh7FoKtQfcvhGBUeOq2Eo2n3c2En0CwXyWY90">

yesterday I think I have tried to change that one too but no runs, but for the one just now, no I haven't change it
ill try it now

**Comment by teodorus-nathaniel** [comment]
@georgeciubotaru I have tried twice

First one, I updated the project in package json after I run the `docker compose up`, result: using your telebit url

https://github.com/user-attachments/assets/91b8a730-b603-4a82-94a2-11e16d32d766

Second one, I created the project beforehand, deleted and restarted the docker, and run the steps, result: no trigger being ran

https://github.com/user-attachments/assets/0ec4548e-39a5-4c20-98d0-a0e734c4c9e0

**Comment by teodorus-nathaniel** [comment]
@georgeciubotaru finally its good now, so the trick maybe have to do with the package json projectId,
If the projectId there is changed, the docker needs to be restarted

But I don't know why the one I did above didn't work, maybe because its the domain that I have used before

https://github.com/user-attachments/assets/96dea67c-d720-4732-805d-d11232200135

**Comment by georgeciubotaru** [comment]
@teodorus-nathaniel Second option

**Comment by teodorus-nathaniel** [comment]
ah okay in that case, I have made the correct handler, thank you 🤝
